services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8
    container_name: jellyfin
    user: "0:0"
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/data/jerryfin-media/:/media:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
