services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8 # 最新の安定バージョンを明示指定
    container_name: jellyfin
    user: "0:0"
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media:ro # 同じ階層の movies フォルダをコンテナの /media にマウント
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
